property.service.base-url=http://property-service:8082
user.service.base-url=http://user-service:8081
notification.service.base-url=http://notification-service:8084
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka